/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package budget;

import javax.swing.JComponent;

/**
 *
 * @author Bill
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public view(String[][] viewSummary, String[][] viewJournal) {
        initComponents();
        viewTabbedPane.addTab("Summary", viewPanelSummary);
        viewTabbedPane.addTab("T-Accounts", viewPanelTAccounts);
        viewTabbedPane.addTab("Journal", viewPanelJournal);
        this.setTitle("View Contents");
        for(int i = 0; i<viewSummary.length; i++){
            viewSummaryTypeTextArea.append(viewSummary[i][0] +"\n");
            
            viewSummaryNameTextArea.append(viewSummary[i][1] +"\n");
            
            viewSummaryDebitTextArea.append(viewSummary[i][2] +"\n");
            
            viewSummaryCreditTextArea.append(viewSummary[i][3] +"\n");
            
        }for(int i = 0; i<viewJournal.length; i++){
            viewJournalNumberTextArea.append(viewJournal[i][0] +"\n");
            viewJournalDateTextArea.append(viewJournal[i][1] + "\n");
            viewJournalDescriptionTextArea.append(viewJournal[i][2] +"\n");
            viewJournalAccountTextArea.append(viewJournal[i][3] +"\n");
            viewJournalDebitTextArea.append(viewJournal[i][4] +"\n");
            viewJournalCreditTextArea.append(viewJournal[i][5] +"\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        viewTabbedPane = new javax.swing.JTabbedPane();
        viewPanelSummary = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewSummaryCreditTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewSummaryDebitTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        viewSummaryNameTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        viewSummaryTypeTextArea = new javax.swing.JTextArea();
        viewPanelJournal = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        viewJournalNumberTextArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        viewJournalDescriptionTextArea = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        viewJournalAccountTextArea = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        viewJournalDebitTextArea = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        viewJournalCreditTextArea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        viewJournalDateTextArea = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        viewPanelTAccounts = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewTabbedPane.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Account Type");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Account Name");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Debit");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Credit");

        viewSummaryCreditTextArea.setColumns(20);
        viewSummaryCreditTextArea.setRows(5);
        jScrollPane1.setViewportView(viewSummaryCreditTextArea);

        viewSummaryDebitTextArea.setColumns(20);
        viewSummaryDebitTextArea.setRows(5);
        jScrollPane2.setViewportView(viewSummaryDebitTextArea);

        viewSummaryNameTextArea.setColumns(20);
        viewSummaryNameTextArea.setRows(5);
        jScrollPane3.setViewportView(viewSummaryNameTextArea);

        viewSummaryTypeTextArea.setColumns(20);
        viewSummaryTypeTextArea.setRows(5);
        jScrollPane4.setViewportView(viewSummaryTypeTextArea);

        javax.swing.GroupLayout viewPanelSummaryLayout = new javax.swing.GroupLayout(viewPanelSummary);
        viewPanelSummary.setLayout(viewPanelSummaryLayout);
        viewPanelSummaryLayout.setHorizontalGroup(
            viewPanelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewPanelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(189, 189, 189)
                .addGroup(viewPanelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(viewPanelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(viewPanelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewPanelSummaryLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(viewPanelSummaryLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addGap(207, 207, 207))))
        );
        viewPanelSummaryLayout.setVerticalGroup(
            viewPanelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewPanelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewPanelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        viewTabbedPane.addTab("tab1", viewPanelSummary);

        viewJournalNumberTextArea.setColumns(20);
        viewJournalNumberTextArea.setRows(5);
        jScrollPane5.setViewportView(viewJournalNumberTextArea);

        viewJournalDescriptionTextArea.setColumns(20);
        viewJournalDescriptionTextArea.setRows(5);
        jScrollPane6.setViewportView(viewJournalDescriptionTextArea);

        viewJournalAccountTextArea.setColumns(20);
        viewJournalAccountTextArea.setRows(5);
        jScrollPane7.setViewportView(viewJournalAccountTextArea);

        viewJournalDebitTextArea.setColumns(20);
        viewJournalDebitTextArea.setRows(5);
        jScrollPane8.setViewportView(viewJournalDebitTextArea);

        viewJournalCreditTextArea.setColumns(20);
        viewJournalCreditTextArea.setRows(5);
        jScrollPane9.setViewportView(viewJournalCreditTextArea);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Transaction #");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Description");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Account Name");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Debit");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Credit");

        viewJournalDateTextArea.setColumns(20);
        viewJournalDateTextArea.setRows(5);
        jScrollPane10.setViewportView(viewJournalDateTextArea);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Date");

        javax.swing.GroupLayout viewPanelJournalLayout = new javax.swing.GroupLayout(viewPanelJournal);
        viewPanelJournal.setLayout(viewPanelJournalLayout);
        viewPanelJournalLayout.setHorizontalGroup(
            viewPanelJournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelJournalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewPanelJournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewPanelJournalLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewPanelJournalLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(viewPanelJournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewPanelJournalLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(viewPanelJournalLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewPanelJournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(viewPanelJournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        viewPanelJournalLayout.setVerticalGroup(
            viewPanelJournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelJournalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(viewPanelJournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(viewPanelJournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane8)
                    .addComponent(jScrollPane9)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );

        viewTabbedPane.addTab("tab2", viewPanelJournal);

        jLabel6.setText("Comming Soon!");

        javax.swing.GroupLayout viewPanelTAccountsLayout = new javax.swing.GroupLayout(viewPanelTAccounts);
        viewPanelTAccounts.setLayout(viewPanelTAccountsLayout);
        viewPanelTAccountsLayout.setHorizontalGroup(
            viewPanelTAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelTAccountsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(1259, Short.MAX_VALUE))
        );
        viewPanelTAccountsLayout.setVerticalGroup(
            viewPanelTAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelTAccountsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(505, Short.MAX_VALUE))
        );

        viewTabbedPane.addTab("tab3", viewPanelTAccounts);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewTabbedPane)
            .addGroup(layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(cancelButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewTabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt){
        new command().setVisible(true);
        view.this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new view().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea viewJournalAccountTextArea;
    private javax.swing.JTextArea viewJournalCreditTextArea;
    private javax.swing.JTextArea viewJournalDateTextArea;
    private javax.swing.JTextArea viewJournalDebitTextArea;
    private javax.swing.JTextArea viewJournalDescriptionTextArea;
    private javax.swing.JTextArea viewJournalNumberTextArea;
    private javax.swing.JPanel viewPanelJournal;
    private javax.swing.JPanel viewPanelSummary;
    private javax.swing.JPanel viewPanelTAccounts;
    private javax.swing.JTextArea viewSummaryCreditTextArea;
    private javax.swing.JTextArea viewSummaryDebitTextArea;
    private javax.swing.JTextArea viewSummaryNameTextArea;
    private javax.swing.JTextArea viewSummaryTypeTextArea;
    private javax.swing.JTabbedPane viewTabbedPane;
    // End of variables declaration//GEN-END:variables
}
